[repository]
name = "hyprsplit"
authors = ["shezdy"]
commit_pins = [
    ["1c460e98f870676b15871fe4e5bfeb1a32a3d6d8", "fd31d08d2f9756ba487541a4d2f5a2cbf0eb16aa"], # 0.36.0
    ["19c90048d65a5660384d2fb865926a366696d6be", "fd31d08d2f9756ba487541a4d2f5a2cbf0eb16aa"], # 0.37.0
    ["c5e28ebcfe00a510922779b2c568cfa52a317445", "fd31d08d2f9756ba487541a4d2f5a2cbf0eb16aa"], # 0.37.1
    ["3875679755014997776e091ff8903acfb311dd2f", "fd31d08d2f9756ba487541a4d2f5a2cbf0eb16aa"], # 0.38.0
    ["360ede79d124ffdeebbe8401f1ac4bc0dbec2c91", "fd31d08d2f9756ba487541a4d2f5a2cbf0eb16aa"], # 0.38.1
    ["e93fbd7c4f991cb8ef03e433ccc4d43587923e15", "3dd002cc6df3fce7d5a49df91201e849f6e2d8e5"], # 0.39.0
    ["fe7b748eb668136dd0558b7c8279bfcd7ab4d759", "6b9db62fab91066bb678f14198771b8e8cc12a8f"], # 0.39.1
    ["cba1ade848feac44b2eda677503900639581c3f4", "ed317e19a8a4e46b339b2d28d1380b5ad1c24eaf"], # 0.40.0
    ["ea2501d4556f84d3de86a4ae2f4b22a474555b9f", "b9753043dc8c2a385f39777aa17f63ae3c104e36"], # 0.41.0
    ["9e781040d9067c2711ec2e9f5b47b76ef70762b3", "38102b8f81e1d48e1c96728513cc663fffe034fc"], # 0.41.1
    ["918d8340afd652b011b937d29d5eea0be08467f5", "3051541ebc7f24dd5325cdfa458f29b4ff9648de"], # 0.41.2
    ["9a09eac79b85c846e3a865a9078a3f8ff65a9259", "fcf00b770e3b89fd93de2de1bb5e68721090f5fe"], # 0.42.0
    ["0f594732b063a90d44df8c5d402d658f27471dfe", "e5c8698c772f7658d1893441ce811ff1eb7c1ba2"], # 0.43.0
    ["0c7a7e2d569eeed9d6025f3eef4ea0690d90845d", "7376aaf982e388046872d534e09e6281666fce72"], # 0.44.0
    ["4520b30d498daca8079365bdb909a8dea38e8d55", "0b315fb97a0f9825668db9ff7436bec5d7e028cb"], # 0.44.1
    ["a425fbebe4cf4238e48a42f724ef2208959d66cf", "b98cc80aab041677cd7648f6e44c18e8f36fa907"], # 0.45.0
    ["500d2a3580388afc8b620b0a3624147faa34f98b", "1ac3dc76d7bd9a5dcffa0f6fb75d35258c519454"], # 0.45.1
    ["12f9a0d0b93f691d4d9923716557154d74777b0a", "1ac3dc76d7bd9a5dcffa0f6fb75d35258c519454"], # 0.45.2
    ["788ae588979c2a1ff8a660f16e3c502ef5796755", "28b1603e7674cc12e0b2b5b384b4dc88b659a62b"], # 0.46.0
    ["254fc2bc6000075f660b4b8ed818a6af544d1d64", "28b1603e7674cc12e0b2b5b384b4dc88b659a62b"]  # 0.46.1
]

[hyprsplit]
description = "split monitor workspaces"
authors = ["shezdy"]
output = "hyprsplit.so"
build = [
    "make all",
]
